makefile = function(Name, Content) -- synapse reference lol
    local Path = '/storage/emulated/0/Android/data/launcher.powerkuy.growlauncher/files/ScriptLua/'..Name
    local File = io.open(Path, 'r')
    local IsDeclared = false

    if File then
        local Data = File:read('*a')
        IsDeclared = Data:find('local SendPacket = SendPacket or sendPacket', 1, true) ~= nil
        File:close()
    end

    File = io.open(Path, 'a+')
    if not IsDeclared then
        File:write('--[[ Info: This file was generated by PacketSpy | Discord : @liebertsx ]]\nlocal SendPacket = SendPacket or sendPacket\n\n')
    end
    File:write('SendPacket('..Content..')\n\n')
    File:close()
end

addHook(function(...)
    local Arguments = {...}
    log('`8[TYPE] : `w'..Arguments[1])
    log('`8[SEND] : `w'..Arguments[2])
    makefile('Packet.lua', Arguments[1]..',[['..Arguments[2]..']]')
end, 'OnSendPacket')
